# Generated by Django 4.1.4 on 2023-02-14 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("auther", models.CharField(max_length=128)),
                ("isbn_number", models.PositiveBigIntegerField(unique=True)),
                ("category", models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classroom", models.CharField(max_length=30)),
                ("branch", models.CharField(max_length=30)),
                ("roll_no", models.CharField(blank=True, max_length=3)),
                ("phone", models.CharField(blank=True, max_length=16)),
                ("image", models.ImageField(blank=True, upload_to="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=13)),
                ("issued_date", models.DateField(auto_now=True)),
                (
                    "expiry_date",
                    models.DateField(
                        default=datetime.datetime(2023, 2, 28, 18, 19, 34, 996794)
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.student",
                    ),
                ),
            ],
        ),
    ]
